"""Add demand forecasts table

Revision ID: 78dc92b36202
Revises: f91de8df2890
Create Date: 2026-07-11 00:53:33.471700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78dc92b36202'
down_revision: Union[str, Sequence[str], None] = 'f91de8df2890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('forecasted_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demand_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_forecasts_destination'), ['destination'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_forecasts_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demand_forecasts_id'))
        batch_op.drop_index(batch_op.f('ix_demand_forecasts_destination'))

    op.drop_table('demand_forecasts')
    # ### end Alembic commands ###
